project_id = "zrfurqydmyxmtxhbqdvr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.nexus-brain]
verify_jwt = false