// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrfurqydmyxmtxhbqdvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyZnVycXlkbXl4bXR4aGJxZHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzkxNzUsImV4cCI6MjA3NDMxNTE3NX0.8U4caBQfKfEhLEMbIKp1i2hX6RYgU5L-T_cB1Tf4acI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});